data_ingestion:
  raw_data_path: artifacts\data\raw.csv
  test_data_path: artifacts\data\test.csv
  train_data_path: artifacts\data\train.csv
data_paths:
  data_path: data/processed/clean_bank_data.csv
data_transformation:
  pca_obj_path: artifacts\preprocessor\pca.pkl
  preprocessor_cluster_obj_path: artifacts\preprocessor\cluster_preprocessor.pkl
  preprocessor_obj_path: artifacts\preprocessor\preprocessor.pkl
  preprocessor_reg_obj_path: artifacts\preprocessor\reg_preprocessor.pkl
model_evaluator:
  churn_evaluation_path: artifacts\evaluations\churn_evaluation.json
  integrated_evaluation_path: artifacts\evaluations\integrated_evaluation.json
  revenue_at_risk_path: artifacts\data\revenue_at_risk.csv
  revenue_evaluation_path: artifacts\evaluations\revenue_evaluation.json
model_trainer:
  churn_model_path: artifacts\models\churn_model.pkl
  cluster_model_path: artifacts\models\cluster_model.pkl
  revenue_model_path: artifacts\models\revenue_model.pkl
timestamp: '20250507_164741'
visualizer:
  output_dir: artifacts\visualizations
